#exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
#paginate: 10
#destination: /home/ben/git-repos/keithmillar.github.com
pygments: true
safe: false
url: http://localhost:4000
excerpt_separator: "{{ more }}"
markdown_ext: markdown,mkd,mkdn,md
markdown: redcarpet
main_title: "Keith Millar"
description: "Keith's Diary and Other Stuff"

